!function(){"use strict";class e{constructor(){this.wrapperEl=document.querySelector("#portfolio-slider .swiper-wrapper"),this.pathToWorksImages="img/dist/works",this.acceptedEl=document.querySelector(".accepted"),this.popUpOverlayEl=document.querySelector(".pop-up__overlay"),this.settings={lazy:{loadPrevNext:!0},spaceBetween:40,speed:800,centeredSlides:!0,roundLengths:!0,loop:!0,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},breakpoints:{320:{slidesPerView:1.5,spaceBetween:80},993:{slidesPerView:1.6,spaceBetween:40},1201:{slidesPerView:2.2},1367:{slidesPerView:3}}}}insertPortfolioIntoPage(e){let t="";for(var i of e)t+=this.getCardMarkup(i);this.wrapperEl.insertAdjacentHTML("beforeend",t);var s=this.addPortfolioSwiper();this.setHeightSlides(),this.setTopDistance(),this.addWindowResizeListener(s),this.addSwiperTransitionStartListener(s),this.addCardsWorksClickListener(e)}addWindowResizeListener(e){window.addEventListener("resize",()=>{this.setHeightSlides(),this.setTopDistance(),e.update()})}addSwiperTransitionStartListener(e){e.on("transitionStart",()=>{this.setHeightSlides(),this.setTopDistance(),e.update()})}getCardMarkup(e){return`
				<div class="swiper-slide" data-id="${e.id}">
					<picture class="portfolio__img">
						<source data-srcset="${this.pathToWorksImages}/${e.id}/${e.image}" media="(min-width: 768px)" width="803" height="570">
						<source data-srcset="${this.pathToWorksImages}/${e.id}/${e.imageMiddle}" media="(min-width: 0)" width="374" height="266">
						<img class="swiper-lazy" data-src="${this.pathToWorksImages}/${e.id}/${e.imageMiddle}" alt="${e.name}" width="374" height="266">
					</picture>
				</div>`}addPortfolioSwiper(){return new Swiper("#portfolio-slider",this.settings)}setHeightSlides(){document.querySelectorAll("#portfolio-slider .swiper-slide").forEach(e=>{var t=e.getBoundingClientRect().width;e.style.height=.71*t+"px"})}setTopDistance(){var e=document.querySelector("#portfolio-slider .swiper-slide-active"),t=document.querySelectorAll("#portfolio-slider .swiper-slide:not(.swiper-slide-active)");let i=e.getBoundingClientRect().height;t.forEach(e=>{var t=e.getBoundingClientRect().height,t=(i-t)/2;e.style.top=t+"px"}),e.style.top="0"}addCardsWorksClickListener(r){document.querySelectorAll("#portfolio-slider .swiper-slide").forEach(s=>{s.addEventListener("click",()=>{var e,t,i=+s.dataset.id;for(e of r)e.id==i&&(t=this.getPopUpWithWork(e),this.popUpOverlayEl.classList.add("active-pop-up"),this.acceptedEl.insertAdjacentHTML("beforebegin",t),this.addImagesElemsClickListener(),this.addCloseElemsClickListener())})})}getPopUpWithWork(e){return`<div class="image">
						<div class="image__body">
							<img src="${this.pathToWorksImages}/${e.id}/${e.image}" alt="${e.name}" class="image__picture">
						</div>
						<button class="image__close" type="button">
							<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg" class="image__close-icon">
								<path d="M1.2915 1.29163L16.7082 16.7083" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"></path>
								<path d="M16.7082 1.29163L1.2915 16.7083" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"></path>
							</svg>
						</button>
					</div>`}addImagesElemsClickListener(){document.querySelectorAll(".image").forEach(i=>{i.addEventListener("click",e=>{var t=i.querySelector(".image__body");e.target==t&&(this.popUpOverlayEl.classList.remove("active-pop-up"),i.style.display="none")})})}addCloseElemsClickListener(){document.querySelectorAll(".image__close").forEach(t=>{t.addEventListener("click",()=>{var e=t.closest(".image");this.popUpOverlayEl.classList.remove("active-pop-up"),e.style.display="none"})})}}window.addEventListener("load",()=>{(new e).insertPortfolioIntoPage(works)})}();